import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { Header } from "@/components/layout/Header";
import { EmptyState } from "@/components/ui/EmptyState";
import { fetchTrends } from "@/lib/api";
import { formatDate } from "@/lib/utils";
import { ChevronRight } from "lucide-react";

export const metadata = {
  title: "Trends",
};

export default async function TrendsPage() {
  let data;
  try {
    data = await fetchTrends(50, 0);
  } catch {
    data = { total: 0, limit: 50, offset: 0, items: [] };
  }

  return (
    <AppShell>
      <Header
        title="Trends"
        subtitle="LLM-summarized clusters of related AI news over recent time windows."
      />

      <div className="px-6 py-6">
        {data.items.length === 0 ? (
          <EmptyState
            title="No trends yet"
            description="Trends are generated by clustering article embeddings. Trigger POST /trends/generate from the backend or scheduler (M21) to populate this page."
          />
        ) : (
          <div className="space-y-3">
            <p className="text-sm text-[var(--text-muted)]">
              {data.total} trend{data.total === 1 ? "" : "s"} tracked
            </p>
            {data.items.map((trend) => (
              <Link
                key={trend.id}
                href={`/trends/${trend.id}`}
                className="group flex items-start justify-between gap-4 rounded-xl border border-[var(--border)] bg-[var(--bg-secondary)] p-5 transition-colors hover:border-[var(--accent)]/30"
              >
                <div className="min-w-0 flex-1">
                  <h2 className="text-base font-semibold text-[var(--text-primary)] group-hover:text-[var(--accent)]">
                    {trend.title}
                  </h2>
                  {trend.description && (
                    <p className="mt-2 line-clamp-2 text-sm text-[var(--text-secondary)]">
                      {trend.description}
                    </p>
                  )}
                  <div className="mt-3 flex flex-wrap gap-3 text-xs text-[var(--text-muted)]">
                    <span>
                      {trend.article_count}{" "}
                      {trend.article_count === 1 ? "article" : "articles"}
                    </span>
                    {trend.period_start && trend.period_end && (
                      <span>
                        {formatDate(trend.period_start)} –{" "}
                        {formatDate(trend.period_end)}
                      </span>
                    )}
                  </div>
                </div>
                <ChevronRight className="mt-1 h-5 w-5 shrink-0 text-[var(--text-muted)] group-hover:text-[var(--accent)]" />
              </Link>
            ))}
          </div>
        )}
      </div>
    </AppShell>
  );
}
